 /*******************************************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_Cfg.h
 *
 * Description: Post Compile Configuration Header file for TM4C123GH6PM Microcontroller - PORT Driver
 *
 * Author: Youssef Behery
 *
 *Date:29/3/2022
 *******************************************************************************************************/
 #include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
	PORT_A_ID , PORT_A0_ID , PORT_A0_MODE , PORT_A0_DIR , PORT_A0_OUTLVL , PORT_A0_INTRES , PORT_A0_DIR_CHANGE , PORT_A0_MODE_CHANGE,
	PORT_A_ID , PORT_A1_ID , PORT_A1_MODE , PORT_A1_DIR , PORT_A1_OUTLVL , PORT_A1_INTRES , PORT_A1_DIR_CHANGE , PORT_A1_MODE_CHANGE,
	PORT_A_ID , PORT_A2_ID , PORT_A2_MODE , PORT_A2_DIR , PORT_A2_OUTLVL , PORT_A2_INTRES , PORT_A2_DIR_CHANGE , PORT_A2_MODE_CHANGE,
	PORT_A_ID , PORT_A3_ID , PORT_A3_MODE , PORT_A3_DIR , PORT_A3_OUTLVL , PORT_A3_INTRES , PORT_A3_DIR_CHANGE , PORT_A3_MODE_CHANGE,
	PORT_A_ID , PORT_A4_ID , PORT_A4_MODE , PORT_A4_DIR , PORT_A4_OUTLVL , PORT_A4_INTRES , PORT_A4_DIR_CHANGE , PORT_A4_MODE_CHANGE,
	PORT_A_ID , PORT_A5_ID , PORT_A5_MODE , PORT_A5_DIR , PORT_A5_OUTLVL , PORT_A5_INTRES , PORT_A5_DIR_CHANGE , PORT_A5_MODE_CHANGE,
	PORT_A_ID , PORT_A6_ID , PORT_A6_MODE , PORT_A6_DIR , PORT_A6_OUTLVL , PORT_A6_INTRES , PORT_A6_DIR_CHANGE , PORT_A6_MODE_CHANGE,
	PORT_A_ID , PORT_A7_ID , PORT_A7_MODE , PORT_A7_DIR , PORT_A7_OUTLVL , PORT_A7_INTRES , PORT_A7_DIR_CHANGE , PORT_A7_MODE_CHANGE,
	
	PORT_B_ID , PORT_B0_ID , PORT_B0_MODE , PORT_B0_DIR , PORT_B0_OUTLVL , PORT_B0_INTRES , PORT_B0_DIR_CHANGE , PORT_B0_MODE_CHANGE,
	PORT_B_ID , PORT_B1_ID , PORT_B1_MODE , PORT_B1_DIR , PORT_B1_OUTLVL , PORT_B1_INTRES , PORT_B1_DIR_CHANGE , PORT_B1_MODE_CHANGE,
	PORT_B_ID , PORT_B2_ID , PORT_B2_MODE , PORT_B2_DIR , PORT_B2_OUTLVL , PORT_B2_INTRES , PORT_B2_DIR_CHANGE , PORT_B2_MODE_CHANGE,
	PORT_B_ID , PORT_B3_ID , PORT_B3_MODE , PORT_B3_DIR , PORT_B3_OUTLVL , PORT_B3_INTRES , PORT_B3_DIR_CHANGE , PORT_B3_MODE_CHANGE,
	PORT_B_ID , PORT_B4_ID , PORT_B4_MODE , PORT_B4_DIR , PORT_B4_OUTLVL , PORT_B4_INTRES , PORT_B4_DIR_CHANGE , PORT_B4_MODE_CHANGE,
	PORT_B_ID , PORT_B5_ID , PORT_B5_MODE , PORT_B5_DIR , PORT_B5_OUTLVL , PORT_B5_INTRES , PORT_B5_DIR_CHANGE , PORT_B5_MODE_CHANGE,
	PORT_B_ID , PORT_B6_ID , PORT_B6_MODE , PORT_B6_DIR , PORT_B6_OUTLVL , PORT_B6_INTRES , PORT_B6_DIR_CHANGE , PORT_B6_MODE_CHANGE,
	PORT_B_ID , PORT_B7_ID , PORT_B7_MODE , PORT_B7_DIR , PORT_B7_OUTLVL , PORT_B7_INTRES , PORT_B7_DIR_CHANGE , PORT_B7_MODE_CHANGE,
	
	PORT_C_ID , PORT_C0_ID , PORT_C0_MODE , PORT_C0_DIR , PORT_C0_OUTLVL , PORT_C0_INTRES , PORT_C0_DIR_CHANGE , PORT_C0_MODE_CHANGE,
	PORT_C_ID , PORT_C1_ID , PORT_C1_MODE , PORT_C1_DIR , PORT_C1_OUTLVL , PORT_C1_INTRES , PORT_C1_DIR_CHANGE , PORT_C1_MODE_CHANGE,
	PORT_C_ID , PORT_C2_ID , PORT_C2_MODE , PORT_C2_DIR , PORT_C2_OUTLVL , PORT_C2_INTRES , PORT_C2_DIR_CHANGE , PORT_C2_MODE_CHANGE,
	PORT_C_ID , PORT_C3_ID , PORT_C3_MODE , PORT_C3_DIR , PORT_C3_OUTLVL , PORT_C3_INTRES , PORT_C3_DIR_CHANGE , PORT_C3_MODE_CHANGE,
	PORT_C_ID , PORT_C4_ID , PORT_C4_MODE , PORT_C4_DIR , PORT_C4_OUTLVL , PORT_C4_INTRES , PORT_C4_DIR_CHANGE , PORT_C4_MODE_CHANGE,
	PORT_C_ID , PORT_C5_ID , PORT_C5_MODE , PORT_C5_DIR , PORT_C5_OUTLVL , PORT_C5_INTRES , PORT_C5_DIR_CHANGE , PORT_C5_MODE_CHANGE,
	PORT_C_ID , PORT_C6_ID , PORT_C6_MODE , PORT_C6_DIR , PORT_C6_OUTLVL , PORT_C6_INTRES , PORT_C6_DIR_CHANGE , PORT_C6_MODE_CHANGE,
	PORT_C_ID , PORT_C7_ID , PORT_C7_MODE , PORT_C7_DIR , PORT_C7_OUTLVL , PORT_C7_INTRES , PORT_C7_DIR_CHANGE , PORT_C7_MODE_CHANGE,
	
	PORT_D_ID , PORT_D0_ID , PORT_D0_MODE , PORT_D0_DIR , PORT_D0_OUTLVL , PORT_D0_INTRES , PORT_D0_DIR_CHANGE , PORT_D0_MODE_CHANGE,
	PORT_D_ID , PORT_D1_ID , PORT_D1_MODE , PORT_D1_DIR , PORT_D1_OUTLVL , PORT_D1_INTRES , PORT_D1_DIR_CHANGE , PORT_D1_MODE_CHANGE,
	PORT_D_ID , PORT_D2_ID , PORT_D2_MODE , PORT_D2_DIR , PORT_D2_OUTLVL , PORT_D2_INTRES , PORT_D2_DIR_CHANGE , PORT_D2_MODE_CHANGE,
	PORT_D_ID , PORT_D3_ID , PORT_D3_MODE , PORT_D3_DIR , PORT_D3_OUTLVL , PORT_D3_INTRES , PORT_D3_DIR_CHANGE , PORT_D3_MODE_CHANGE,
	PORT_D_ID , PORT_D4_ID , PORT_D4_MODE , PORT_D4_DIR , PORT_D4_OUTLVL , PORT_D4_INTRES , PORT_D4_DIR_CHANGE , PORT_D4_MODE_CHANGE,
	PORT_D_ID , PORT_D5_ID , PORT_D5_MODE , PORT_D5_DIR , PORT_D5_OUTLVL , PORT_D5_INTRES , PORT_D5_DIR_CHANGE , PORT_D5_MODE_CHANGE,
	PORT_D_ID , PORT_D6_ID , PORT_D6_MODE , PORT_D6_DIR , PORT_D6_OUTLVL , PORT_D6_INTRES , PORT_D6_DIR_CHANGE , PORT_D6_MODE_CHANGE,
	PORT_D_ID , PORT_D7_ID , PORT_D7_MODE , PORT_D7_DIR , PORT_D7_OUTLVL , PORT_D7_INTRES , PORT_D7_DIR_CHANGE , PORT_D7_MODE_CHANGE,
	
	PORT_E_ID , PORT_E0_ID , PORT_E0_MODE , PORT_E0_DIR , PORT_E0_OUTLVL , PORT_E0_INTRES , PORT_E0_DIR_CHANGE , PORT_E0_MODE_CHANGE,
	PORT_E_ID , PORT_E1_ID , PORT_E1_MODE , PORT_E1_DIR , PORT_E1_OUTLVL , PORT_E1_INTRES , PORT_E1_DIR_CHANGE , PORT_E1_MODE_CHANGE,
	PORT_E_ID , PORT_E2_ID , PORT_E2_MODE , PORT_E2_DIR , PORT_E2_OUTLVL , PORT_E2_INTRES , PORT_E2_DIR_CHANGE , PORT_E2_MODE_CHANGE,
	PORT_E_ID , PORT_E3_ID , PORT_E3_MODE , PORT_E3_DIR , PORT_E3_OUTLVL , PORT_E3_INTRES , PORT_E3_DIR_CHANGE , PORT_E3_MODE_CHANGE,
	PORT_E_ID , PORT_E4_ID , PORT_E4_MODE , PORT_E4_DIR , PORT_E4_OUTLVL , PORT_E4_INTRES , PORT_E4_DIR_CHANGE , PORT_E4_MODE_CHANGE,
	PORT_E_ID , PORT_E5_ID , PORT_E5_MODE , PORT_E5_DIR , PORT_E5_OUTLVL , PORT_E5_INTRES , PORT_E5_DIR_CHANGE , PORT_E5_MODE_CHANGE,
	
	PORT_F_ID , PORT_F0_ID , PORT_F0_MODE , PORT_F0_DIR , PORT_F0_OUTLVL , PORT_F0_INTRES , PORT_F0_DIR_CHANGE , PORT_F0_MODE_CHANGE,
	PORT_F_ID , PORT_F1_ID , PORT_F1_MODE , PORT_F1_DIR , PORT_F1_OUTLVL , PORT_F1_INTRES , PORT_F1_DIR_CHANGE , PORT_F1_MODE_CHANGE,
	PORT_F_ID , PORT_F2_ID , PORT_F2_MODE , PORT_F2_DIR , PORT_F2_OUTLVL , PORT_F2_INTRES , PORT_F2_DIR_CHANGE , PORT_F2_MODE_CHANGE,
	PORT_F_ID , PORT_F3_ID , PORT_F3_MODE , PORT_F3_DIR , PORT_F3_OUTLVL , PORT_F3_INTRES , PORT_F3_DIR_CHANGE , PORT_F3_MODE_CHANGE,
	PORT_F_ID , PORT_F4_ID , PORT_F4_MODE , PORT_F4_DIR , PORT_F4_OUTLVL , PORT_F4_INTRES , PORT_F4_DIR_CHANGE , PORT_F4_MODE_CHANGE
	
};